// ============================================================
// PICCOLI EROI 2 - Dati di gioco
// Classi (8), Specie (6), Incantesimi, Mostri, Oggetti
// ============================================================

export const STAT_NAMES = {
  FOR:'Forza', DES:'Destrezza', COS:'Costituzione',
  INT:'Intelligenza', SAG:'Saggezza', CAR:'Carisma',
};

export const LABEL = {
  hp:'Punti Ferita', ac:'Classe Armatura', xp:'Esperienza', gold:'Oro',
  slots:'Slot Incantesimo', pb:'Competenza',
};

// ------------------------------------------------------------
// SPECIE
// I tratti sono implementati come flag letti dal motore di gioco
// ------------------------------------------------------------
export const SPECIES = [
  { id:'umano', name:'Umano', sprite:'umano',
    desc:'Versatile e pieno di risorse. Una volta per riposo lungo puoi ritirare un dado andato male (Ispirazione Eroica).',
    traits:{ heroicInspiration:true },
    traitNames:['Ispirazione Eroica: 1 ritiro di dado per riposo lungo'] },
  { id:'elfo', name:'Elfo', sprite:'elfo',
    desc:'Grazia antica e sensi acuti. La tua mente fatata resiste agli incantamenti.',
    traits:{ advSaves:['SAG'] },
    traitNames:['Ascendenza Fatata: vantaggio ai tiri salvezza su Saggezza'] },
  { id:'nano', name:'Nano', sprite:'nano',
    desc:'Robusto come la roccia. Il veleno non ti fa quasi nulla e hai piu\' punti ferita.',
    traits:{ hpPerLevel:1, advVsPoison:true },
    traitNames:['Tenacia Nanica: +1 PF per livello', 'Resilienza: vantaggio ai tiri salvezza contro il veleno'] },
  { id:'halfling', name:'Halfling', sprite:'halfling',
    desc:'Piccolo e incredibilmente fortunato: quando esce 1 sul dado, lo ritiri!',
    traits:{ lucky:true, advVsFear:true },
    traitNames:['Fortunato: ritiri automaticamente gli 1 sul d20', 'Coraggioso: vantaggio contro la paura'] },
  { id:'dragonide', name:'Dragonide', sprite:'dragonide',
    desc:'Discendente dei draghi! Puoi soffiare fuoco e il fuoco ti fa meno male.',
    traits:{ breathWeapon:true, fireResist:true },
    traitNames:['Soffio di Fuoco: 2d6 danni in area, 1 uso per riposo', 'Resistenza al fuoco: danni da fuoco dimezzati'] },
  { id:'gnomo', name:'Gnomo', sprite:'gnomo',
    desc:'Mente brillante e scattante. Gli incantesimi nemici faticano a ingannarti.',
    traits:{ advSaves:['INT'] },
    traitNames:['Astuzia Gnomesca: vantaggio ai tiri salvezza su Intelligenza'] },
];

// ------------------------------------------------------------
// CLASSI
// hitDie: dado vita | casterType: full/half/none
// saveProfs: tiri salvezza con competenza | atkStat: stat per attaccare
// weapon: {name, num, faces} | acBase: CA di partenza (armatura inclusa)
// features: capacita' per livello | spellsByLevel: nuovi incantesimi
// ------------------------------------------------------------
export const CLASSES = [
  { id:'guerriero', name:'Guerriero', color:'#e94560', sprite:'guerriero',
    desc:'Maestro d\'armi, forte e protetto da una solida armatura.',
    hitDie:10, casterType:'none', atkStat:'FOR',
    saveProfs:['FOR','COS'], acBase:16, acUseDex:false,
    stats:{FOR:16,DES:12,COS:14,INT:8,SAG:10,CAR:10},
    weapon:{name:'Spada Lunga', num:1, faces:8},
    cantrips:[], spellsByLevel:{},
    features:[
      { level:1, id:'second_wind', name:'Secondo Vento',
        desc:'Una volta per riposo, con un\'azione bonus recuperi 1d10 + livello PF.' },
      { level:2, id:'action_surge', name:'Azione Impetuosa',
        desc:'Una volta per riposo puoi fare un attacco extra nello stesso turno.' },
      { level:5, id:'extra_attack', name:'Attacco Extra',
        desc:'Quando attacchi, colpisci due volte!' },
    ] },
  { id:'barbaro', name:'Barbaro', color:'#ff6600', sprite:'barbaro',
    desc:'Furia selvaggia e muscoli enormi. Niente armatura, tanto coraggio.',
    hitDie:12, casterType:'none', atkStat:'FOR',
    saveProfs:['FOR','COS'], acBase:13, acUseDex:true,
    stats:{FOR:16,DES:14,COS:14,INT:8,SAG:10,CAR:8},
    weapon:{name:'Grande Ascia', num:1, faces:12},
    cantrips:[], spellsByLevel:{},
    features:[
      { level:1, id:'rage', name:'Furia',
        desc:'Azione bonus: entri in furia per 3 round. +2 ai danni in mischia e i danni che subisci sono dimezzati. 2 usi per riposo lungo.' },
      { level:2, id:'reckless', name:'Attacco Spericolato',
        desc:'Puoi attaccare con vantaggio, ma anche i nemici avranno vantaggio contro di te in quel round.' },
      { level:5, id:'extra_attack', name:'Attacco Extra',
        desc:'Quando attacchi, colpisci due volte!' },
    ] },
  { id:'ladro', name:'Ladro', color:'#888', sprite:'ladro',
    desc:'Furtivo e letale: colpisce dove fa piu\' male, quando il nemico non se lo aspetta.',
    hitDie:8, casterType:'none', atkStat:'DES',
    saveProfs:['DES','INT'], acBase:12, acUseDex:true,
    stats:{FOR:10,DES:16,COS:12,INT:13,SAG:10,CAR:14},
    weapon:{name:'Pugnali Gemelli', num:1, faces:6},
    cantrips:[], spellsByLevel:{},
    features:[
      { level:1, id:'sneak_attack', name:'Attacco Furtivo',
        desc:'Se hai vantaggio al tiro per colpire, infliggi 1d6 danni extra (2d6 al liv. 3, 3d6 al liv. 5).' },
      { level:2, id:'cunning_action', name:'Azione Scaltra',
        desc:'Azione bonus: ti nascondi! Il tuo prossimo attacco avra\' vantaggio.' },
      { level:5, id:'uncanny_dodge', name:'Schivata Prodigiosa',
        desc:'Il primo colpo che subisci ogni round ti fa meta\' danni.' },
    ] },
  { id:'maga', name:'Maga', color:'#7b2d8b', sprite:'maga',
    desc:'Studiosa dell\'arcano: i suoi incantesimi bruciano, proteggono e stupiscono.',
    hitDie:6, casterType:'full', atkStat:'INT', spellStat:'INT',
    saveProfs:['INT','SAG'], acBase:10, acUseDex:true,
    stats:{FOR:8,DES:14,COS:12,INT:16,SAG:12,CAR:10},
    weapon:{name:'Bastone', num:1, faces:6},
    cantrips:['dardo_di_fuoco','mano_magica'],
    spellsByLevel:{ 1:['dardo_incantato','scudo_magico','mani_brucianti'], 3:['raggio_rovente','ragnatela'], 5:['palla_di_fuoco'] },
    features:[
      { level:1, id:'arcane_recovery', name:'Recupero Arcano',
        desc:'Durante un riposo breve recuperi 1 slot incantesimo di livello 1.' },
      { level:4, id:'asi', name:'Mente Affilata', desc:'Le tue magie diventano piu\' potenti.' },
    ] },
  { id:'chierico', name:'Chierico', color:'#f5c542', sprite:'chierico',
    desc:'Campione della luce: cura le ferite e scaccia le creature oscure.',
    hitDie:8, casterType:'full', atkStat:'FOR', spellStat:'SAG',
    saveProfs:['SAG','CAR'], acBase:16, acUseDex:false,
    stats:{FOR:14,DES:8,COS:14,INT:10,SAG:16,CAR:12},
    weapon:{name:'Mazza', num:1, faces:6},
    cantrips:['fiamma_sacra','luce'],
    spellsByLevel:{ 1:['cura_ferite','benedizione','scudo_della_fede'], 3:['cura_maggiore','aiuto_divino'], 5:['colonna_di_luce'] },
    features:[
      { level:1, id:'turn_undead_lite', name:'Luce Divina',
        desc:'I tuoi incantesimi fanno danni extra ai non morti (scheletri, zombi, fantasmi).' },
      { level:2, id:'channel_divinity', name:'Incanalare Divinita\'',
        desc:'Una volta per riposo: curi tutti gli alleati di 1d8 PF con una preghiera.' },
    ] },
  { id:'ranger', name:'Ranger', color:'#2d6a27', sprite:'ranger',
    desc:'Esploratore dei boschi: arco infallibile e un fiuto speciale per le prede.',
    hitDie:10, casterType:'half', atkStat:'DES', spellStat:'SAG',
    saveProfs:['FOR','DES'], acBase:12, acUseDex:true,
    stats:{FOR:12,DES:16,COS:13,INT:8,SAG:14,CAR:10},
    weapon:{name:'Arco Lungo', num:1, faces:8},
    cantrips:[],
    spellsByLevel:{ 2:['marchio_del_cacciatore','cura_ferite'], 5:['freccia_tonante'] },
    features:[
      { level:1, id:'favored_enemy', name:'Nemico Prescelto',
        desc:'Il tuo primo attacco contro ogni nemico nuovo ha vantaggio: lo hai studiato!' },
      { level:5, id:'extra_attack', name:'Attacco Extra',
        desc:'Quando attacchi, colpisci due volte!' },
    ] },
  { id:'bardo', name:'Bardo', color:'#ff69b4', sprite:'bardo',
    desc:'Musica magica: ispira gli amici, confonde i nemici e ruba la scena.',
    hitDie:8, casterType:'full', atkStat:'DES', spellStat:'CAR',
    saveProfs:['DES','CAR'], acBase:12, acUseDex:true,
    stats:{FOR:8,DES:14,COS:12,INT:10,SAG:12,CAR:16},
    weapon:{name:'Stocco', num:1, faces:8},
    cantrips:['beffa_crudele'],
    spellsByLevel:{ 1:['parola_guaritrice','fascino','benedizione'], 3:['ritmo_travolgente'], 5:['cura_maggiore'] },
    features:[
      { level:1, id:'bardic_inspiration', name:'Ispirazione Bardica',
        desc:'Azione bonus: dai a un alleato un d6 di ispirazione da aggiungere a un tiro. 3 usi per riposo lungo.' },
      { level:2, id:'song_of_rest', name:'Canzone di Riposo',
        desc:'Durante i riposi brevi, la tua musica fa recuperare 1d6 PF extra a tutti.' },
    ] },
  { id:'paladino', name:'Paladino', color:'#7ec8e3', sprite:'paladino',
    desc:'Cavaliere sacro: giuramento, armatura splendente e mani che guariscono.',
    hitDie:10, casterType:'half', atkStat:'FOR', spellStat:'CAR',
    saveProfs:['SAG','CAR'], acBase:16, acUseDex:false,
    stats:{FOR:16,DES:8,COS:14,INT:8,SAG:10,CAR:14},
    weapon:{name:'Spada Lunga', num:1, faces:8},
    cantrips:[],
    spellsByLevel:{ 2:['scudo_della_fede','cura_ferite'], 5:['colonna_di_luce'] },
    features:[
      { level:1, id:'lay_on_hands', name:'Imposizione delle Mani',
        desc:'Hai una riserva di 5 PF per livello: puoi curare chi vuoi, quanto vuoi, finche\' non finisce. Si ricarica col riposo lungo.' },
      { level:2, id:'divine_smite', name:'Punizione Divina',
        desc:'Quando colpisci, puoi spendere uno slot incantesimo per infliggere +2d8 danni radiosi.' },
      { level:5, id:'extra_attack', name:'Attacco Extra',
        desc:'Quando attacchi, colpisci due volte!' },
    ] },
];

// ------------------------------------------------------------
// INCANTESIMI
// level 0 = trucchetto (gratis), 1-2 = richiede slot di quel livello
// type: attack (tiro per colpire) | save (tiro salvezza nemico) |
//       auto (colpisce sempre) | heal | buff | special
// ------------------------------------------------------------
export const SPELLS = {
  // Trucchetti
  dardo_di_fuoco: { name:'Dardo di Fuoco', level:0, type:'attack', target:'enemy',
    dmg:{num:1,faces:10}, dmgType:'fuoco',
    desc:'Scagli un dardo infuocato: 1d10 danni da fuoco.' },
  fiamma_sacra: { name:'Fiamma Sacra', level:0, type:'save', save:'DES', target:'enemy',
    dmg:{num:1,faces:8}, dmgType:'radioso', halfOnSave:false,
    desc:'Una fiamma scende dal cielo: 1d8 danni radiosi se il nemico non schiva.' },
  beffa_crudele: { name:'Beffa Crudele', level:0, type:'save', save:'SAG', target:'enemy',
    dmg:{num:1,faces:6}, dmgType:'psichico', onHit:{condition:'frightened', rounds:1},
    desc:'Un insulto magico cosi\' bruciante che fa 1d6 danni e spaventa il nemico!' },
  luce: { name:'Luce', level:0, type:'special', target:'special',
    desc:'Illumini la stanza: utile per esplorare e contro i fantasmi.' },
  mano_magica: { name:'Mano Magica', level:0, type:'special', target:'special',
    desc:'Una mano spettrale che puo\' aprire forzieri e leve a distanza.' },

  // Livello 1
  dardo_incantato: { name:'Dardo Incantato', level:1, type:'auto', target:'enemy',
    dmg:{num:3,faces:4,bonus:3}, dmgType:'forza',
    desc:'Tre dardi di pura magia che colpiscono SEMPRE: 3d4+3 danni.' },
  mani_brucianti: { name:'Mani Brucianti', level:1, type:'save', save:'DES', target:'all_enemies',
    dmg:{num:3,faces:6}, dmgType:'fuoco', halfOnSave:true,
    desc:'Un ventaglio di fiamme su TUTTI i nemici: 3d6 danni (meta\' se schivano).' },
  scudo_magico: { name:'Scudo Magico', level:1, type:'buff', target:'self',
    buff:{condition:'shielded', rounds:3},
    desc:'Uno scudo invisibile ti protegge: +2 Classe Armatura per 3 round.' },
  scudo_della_fede: { name:'Scudo della Fede', level:1, type:'buff', target:'ally',
    buff:{condition:'shielded', rounds:3},
    desc:'Proteggi un alleato con la fede: +2 Classe Armatura per 3 round.' },
  cura_ferite: { name:'Cura Ferite', level:1, type:'heal', target:'ally',
    heal:{num:2,faces:4,addMod:true},
    desc:'Tocchi un alleato e le ferite si chiudono: cura 2d4 + il tuo modificatore.' },
  parola_guaritrice: { name:'Parola Guaritrice', level:1, type:'heal', target:'ally',
    heal:{num:1,faces:4,addMod:true},
    desc:'Una parola magica cura un alleato anche da lontano: 1d4 + modificatore.' },
  benedizione: { name:'Benedizione', level:1, type:'buff', target:'party',
    buff:{condition:'blessed', rounds:3},
    desc:'Tutta la squadra e\' benedetta: +1d4 ai tiri per colpire per 3 round.' },
  fascino: { name:'Fascino', level:1, type:'save', save:'SAG', target:'enemy',
    onHit:{condition:'frightened', rounds:2}, noDamage:true,
    desc:'Incanti un nemico: se fallisce il tiro salvezza, e\' confuso e attacca con svantaggio.' },
  marchio_del_cacciatore: { name:'Marchio del Cacciatore', level:1, type:'buff', target:'self',
    buff:{condition:'huntersMark', rounds:5},
    desc:'Marchi la tua preda: i tuoi attacchi fanno +1d6 danni per 5 round.' },

  // Livello 2
  raggio_rovente: { name:'Raggio Rovente', level:2, type:'attack', target:'enemy',
    dmg:{num:4,faces:6}, dmgType:'fuoco',
    desc:'Raggi di fuoco concentrati su un nemico: 4d6 danni da fuoco.' },
  ragnatela: { name:'Ragnatela', level:2, type:'save', save:'DES', target:'enemy',
    onHit:{condition:'prone', rounds:2}, dmg:{num:1,faces:4}, dmgType:'forza',
    desc:'Ragnatele appiccicose intrappolano un nemico a terra per 2 round.' },
  cura_maggiore: { name:'Cura Maggiore', level:2, type:'heal', target:'ally',
    heal:{num:4,faces:4,addMod:true},
    desc:'Una cura potente: 4d4 + modificatore punti ferita.' },
  aiuto_divino: { name:'Aiuto Divino', level:2, type:'heal', target:'party',
    heal:{num:1,faces:4,bonus:3},
    desc:'Una luce dorata avvolge la squadra: tutti recuperano 1d4+3 PF.' },
  ritmo_travolgente: { name:'Ritmo Travolgente', level:2, type:'buff', target:'party',
    buff:{condition:'blessed', rounds:4},
    desc:'Un ritmo irresistibile carica la squadra: +1d4 ai tiri per colpire per 4 round.' },

  // Livello 3 (sbloccati al liv. 5, usano slot di livello 2)
  palla_di_fuoco: { name:'Palla di Fuoco', level:2, type:'save', save:'DES', target:'all_enemies',
    dmg:{num:6,faces:6}, dmgType:'fuoco', halfOnSave:true,
    desc:'LA magia piu\' famosa: esplosione su tutti i nemici, 6d6 danni (meta\' se schivano).' },
  colonna_di_luce: { name:'Colonna di Luce', level:2, type:'save', save:'COS', target:'enemy',
    dmg:{num:4,faces:8}, dmgType:'radioso', halfOnSave:true,
    desc:'Una colonna di luce divina: 4d8 danni radiosi (doppi sui non morti!).' },
  freccia_tonante: { name:'Freccia Tonante', level:2, type:'attack', target:'enemy',
    dmg:{num:3,faces:8}, dmgType:'tuono', onHit:{condition:'prone', rounds:1},
    desc:'Una freccia carica di tuono: 3d8 danni e il nemico cade a terra!' },
};

// ------------------------------------------------------------
// MOSTRI
// dmg: {num, faces, bonus} | atkMod: bonus al tiro per colpire
// traits: comportamenti speciali letti dal motore di combattimento
// undead: true per i non morti (Luce Divina del chierico)
// ------------------------------------------------------------
export const MONSTERS = {
  // --- Capitolo 1: boschi e grotte ---
  goblin: { name:'Goblin', sprite:'goblin', hp:7, ac:13, atkMod:4,
    dmg:{num:1,faces:6,bonus:2}, atkName:'Scimitarra Arrugginita', xp:25, gold:5,
    stats:{FOR:8,DES:14,COS:10,INT:10,SAG:8,CAR:8},
    desc:'Piccolo, verde e dispettoso. Attacca in gruppo!' },
  goblin_arciere: { name:'Goblin Arciere', sprite:'goblin_arciere', hp:6, ac:13, atkMod:4,
    dmg:{num:1,faces:6,bonus:2}, atkName:'Arco Corto', xp:25, gold:5,
    stats:{FOR:8,DES:14,COS:10,INT:10,SAG:8,CAR:8},
    desc:'Tira frecce da lontano ridacchiando.' },
  lupo: { name:'Lupo', sprite:'lupo', hp:11, ac:13, atkMod:4,
    dmg:{num:2,faces:4,bonus:2}, atkName:'Morso', xp:50, gold:0,
    stats:{FOR:12,DES:15,COS:12,INT:3,SAG:12,CAR:6},
    traits:{ packTactics:true },
    desc:'Caccia in branco: ha vantaggio se un alleato e\' vicino alla preda.' },
  ragno_gigante: { name:'Ragno Gigante', sprite:'ragno', hp:11, ac:12, atkMod:4,
    dmg:{num:1,faces:8,bonus:1}, atkName:'Morso Velenoso', xp:50, gold:0,
    stats:{FOR:12,DES:16,COS:12,INT:2,SAG:11,CAR:4},
    traits:{ poisonOnHit:{dc:11, rounds:2} },
    desc:'Grande come un cane! Il suo morso avvelena: tiro salvezza su Costituzione o sei avvelenato.' },
  slime: { name:'Slime Verde', sprite:'slime', hp:14, ac:8, atkMod:3,
    dmg:{num:1,faces:6,bonus:1}, atkName:'Schizzo Acido', xp:30, gold:0,
    stats:{FOR:12,DES:6,COS:14,INT:1,SAG:6,CAR:1},
    desc:'Una gelatina che scioglie tutto quello che tocca. Lento ma appiccicoso.' },
  kobold: { name:'Kobold', sprite:'kobold', hp:5, ac:12, atkMod:4,
    dmg:{num:1,faces:4,bonus:2}, atkName:'Lancia Corta', xp:15, gold:3,
    stats:{FOR:7,DES:15,COS:9,INT:8,SAG:7,CAR:8},
    traits:{ packTactics:true },
    desc:'Piccola lucertola codarda: pericoloso solo in gruppo.' },
  capo_goblin: { name:'Re Sghignazzo, Capo Goblin', sprite:'capo_goblin', hp:21, ac:15, atkMod:5,
    dmg:{num:1,faces:8,bonus:3}, atkName:'Ascia Reale', xp:100, gold:40, boss:true,
    stats:{FOR:14,DES:14,COS:12,INT:10,SAG:8,CAR:10},
    traits:{ multiattack:2 },
    desc:'Il re dei goblin con la sua corona storta! Attacca DUE volte per turno.' },

  // --- Capitolo 2: cripte e non morti ---
  scheletro: { name:'Scheletro', sprite:'scheletro', hp:13, ac:13, atkMod:4,
    dmg:{num:1,faces:6,bonus:2}, atkName:'Spada d\'Osso', xp:50, gold:0, undead:true,
    stats:{FOR:10,DES:14,COS:15,INT:6,SAG:8,CAR:5},
    desc:'Ossa antiche tenute insieme da magia oscura.' },
  scheletro_arciere: { name:'Scheletro Arciere', sprite:'scheletro_arciere', hp:11, ac:13, atkMod:4,
    dmg:{num:1,faces:8,bonus:2}, atkName:'Arco Antico', xp:50, gold:0, undead:true,
    stats:{FOR:10,DES:14,COS:15,INT:6,SAG:8,CAR:5},
    desc:'Mira benissimo, per uno senza occhi.' },
  zombi: { name:'Zombi', sprite:'zombi', hp:22, ac:8, atkMod:3,
    dmg:{num:1,faces:6,bonus:1}, atkName:'Pugno Marcio', xp:50, gold:0, undead:true,
    stats:{FOR:13,DES:6,COS:16,INT:3,SAG:6,CAR:5},
    traits:{ undeadFortitude:true },
    desc:'Lento ma testardo: quando dovrebbe cadere, a volte si rialza con 1 PF!' },
  pipistrello_gigante: { name:'Pipistrello Gigante', sprite:'pipistrello', hp:9, ac:13, atkMod:4,
    dmg:{num:1,faces:6,bonus:2}, atkName:'Zanne', xp:25, gold:0,
    stats:{FOR:15,DES:16,COS:11,INT:2,SAG:12,CAR:6},
    desc:'Svolazza nel buio stridendo. Difficile da colpire!' },
  mimic: { name:'Mimic', sprite:'mimic', hp:18, ac:12, atkMod:5,
    dmg:{num:1,faces:8,bonus:3}, atkName:'Morso a Sorpresa', xp:75, gold:30,
    stats:{FOR:17,DES:12,COS:15,INT:5,SAG:13,CAR:8},
    desc:'Sembrava un forziere... e invece ha i denti! Sorpresa!' },
  fantasma: { name:'Fantasma', sprite:'fantasma', hp:16, ac:14, atkMod:5,
    dmg:{num:2,faces:6,bonus:1}, atkName:'Tocco Gelido', xp:75, gold:0, undead:true,
    stats:{FOR:7,DES:13,COS:10,INT:10,SAG:12,CAR:17},
    traits:{ fearAura:{dc:11} },
    desc:'Uno spirito lamentoso: all\'inizio del combattimento puo\' spaventarti (tiro salvezza su Saggezza).' },
  cavaliere_ossa: { name:'Sir Ossarius, Cavaliere d\'Ossa', sprite:'cavaliere_ossa', hp:36, ac:16, atkMod:6,
    dmg:{num:1,faces:10,bonus:3}, atkName:'Spadone Maledetto', xp:200, gold:80, boss:true, undead:true,
    stats:{FOR:16,DES:11,COS:15,INT:8,SAG:10,CAR:12},
    traits:{ multiattack:2, fearAura:{dc:12} },
    desc:'Un antico cavaliere maledetto. La sua armatura nera scricchiola, la sua spada gela il sangue.' },

  // --- Capitolo 3: la montagna del drago ---
  kobold_dragonico: { name:'Kobold Dragonico', sprite:'kobold_drago', hp:13, ac:14, atkMod:5,
    dmg:{num:1,faces:6,bonus:3}, atkName:'Lancia Dentata', xp:50, gold:8,
    stats:{FOR:12,DES:16,COS:12,INT:9,SAG:9,CAR:10},
    traits:{ packTactics:true },
    desc:'Kobold d\'elite che venera il drago. Piu\' coraggioso dei suoi cugini.' },
  orco_mercenario: { name:'Orco Mercenario', sprite:'orco', hp:15, ac:13, atkMod:5,
    dmg:{num:1,faces:12,bonus:3}, atkName:'Grande Ascia', xp:100, gold:20,
    stats:{FOR:16,DES:12,COS:16,INT:7,SAG:11,CAR:10},
    desc:'Pagato in oro dal drago per fermare gli intrusi. Colpisce fortissimo.' },
  salamandra: { name:'Salamandra di Fuoco', sprite:'salamandra', hp:20, ac:14, atkMod:5,
    dmg:{num:2,faces:6,bonus:2}, atkName:'Coda Incandescente', xp:100, gold:0,
    stats:{FOR:14,DES:14,COS:15,INT:7,SAG:10,CAR:8},
    traits:{ fireBody:true },
    desc:'Una lucertola di fiamma viva: chi la colpisce in mischia si scotta (1d4 danni da fuoco).' },
  cucciolo_drago: { name:'Cucciolo di Drago', sprite:'cucciolo_drago', hp:24, ac:15, atkMod:6,
    dmg:{num:1,faces:10,bonus:3}, atkName:'Morso', xp:150, gold:30,
    stats:{FOR:15,DES:12,COS:13,INT:10,SAG:11,CAR:13},
    traits:{ breath:{dmg:{num:3,faces:6}, save:'DES', dc:12, recharge:3} },
    desc:'Piccolo ma gia\' sputa fuoco! Ogni tanto usa il soffio: 3d6 danni a tutti (tiro salvezza su Destrezza per dimezzare).' },
  drago_rosso: { name:'Vermilius, il Drago Rosso', sprite:'drago', hp:65, ac:17, atkMod:7,
    dmg:{num:2,faces:6,bonus:4}, atkName:'Artigli e Zanne', xp:450, gold:300, boss:true,
    stats:{FOR:19,DES:10,COS:17,INT:12,SAG:11,CAR:15},
    traits:{ multiattack:2, breath:{dmg:{num:6,faces:6}, save:'DES', dc:13, recharge:3}, fearAura:{dc:13} },
    desc:'Il giovane drago rosso che terrorizza la valle. Soffio di fuoco devastante, scaglie come scudi. Il suo tesoro e\' leggendario.' },
};

// ------------------------------------------------------------
// OGGETTI
// type: consumable | weapon | armor | accessory | quest
// ------------------------------------------------------------
export const ITEMS = {
  pozione_cura: { name:'Pozione di Cura', type:'consumable', effect:'heal',
    dice:{num:2,faces:4,bonus:2}, price:25, sprite:'potion_hp',
    desc:'Liquido rosso frizzante: cura 2d4+2 PF.' },
  pozione_cura_maggiore: { name:'Pozione di Cura Maggiore', type:'consumable', effect:'heal',
    dice:{num:4,faces:4,bonus:4}, price:60, sprite:'potion_hp',
    desc:'Versione extra-forte: cura 4d4+4 PF.' },
  antidoto: { name:'Antidoto', type:'consumable', effect:'cure_poison', price:15, sprite:'potion_mp',
    desc:'Sapore terribile, ma cura il veleno all\'istante.' },
  pergamena_lucente: { name:'Pergamena Lucente', type:'consumable', effect:'restore_slot', slotLevel:1,
    price:40, sprite:'scroll', desc:'Leggi le rune e recuperi 1 slot incantesimo di livello 1.' },
  pergamena_splendente: { name:'Pergamena Splendente', type:'consumable', effect:'restore_slot', slotLevel:2,
    price:80, sprite:'scroll', desc:'Rune potenti: recuperi 1 slot incantesimo di livello 2.' },
  bomba_alchemica: { name:'Bomba Alchemica', type:'consumable', effect:'damage_all',
    dice:{num:2,faces:6}, price:50, sprite:'bomb',
    desc:'Lanciala in combattimento: 2d6 danni da fuoco a TUTTI i nemici.' },
  acqua_benedetta: { name:'Acqua Benedetta', type:'consumable', effect:'damage_undead',
    dice:{num:2,faces:8}, price:30, sprite:'potion_mp',
    desc:'Brucia i non morti: 2d8 danni a scheletri, zombi e fantasmi.' },
  arma_magica_1: { name:'Arma Magica +1', type:'weapon', effect:'atk_bonus', value:1, price:120, sprite:'sword',
    desc:'Brilla di rune azzurre: +1 ai tiri per colpire e ai danni.' },
  scudo_runico: { name:'Scudo Runico', type:'armor', effect:'ac_bonus', value:1, price:100, sprite:'shield',
    desc:'+1 alla Classe Armatura. Le rune respingono i colpi.' },
  mantello_elfico: { name:'Mantello Elfico', type:'accessory', effect:'ac_bonus', value:1, price:90, sprite:'cloak',
    desc:'Leggero come la nebbia: +1 alla Classe Armatura.' },
  amuleto_vita: { name:'Amuleto della Vita', type:'accessory', effect:'hp_bonus', value:5, price:80, sprite:'amulet',
    desc:'+5 Punti Ferita massimi. Pulsa come un piccolo cuore.' },
  anello_fortuna: { name:'Anello della Fortuna', type:'accessory', effect:'lucky_ring', price:150, sprite:'ring',
    desc:'Una volta per combattimento, ritira automaticamente un 1 sul d20.' },
  // Oggetti quest
  chiave_cripta: { name:'Chiave della Cripta', type:'quest', sprite:'key',
    desc:'Una chiave d\'argento antica, fredda al tatto. Apre la porta delle Cripte.' },
  gemma_drago: { name:'Gemma del Drago', type:'quest', sprite:'gem',
    desc:'Una gemma rossa che pulsa di calore. Indica la strada verso la tana.' },
  uovo_drago: { name:'Uovo di Drago', type:'quest', sprite:'egg',
    desc:'Un uovo caldo e screziato d\'oro. Dentro si muove qualcosa...' },
};

// XP che serve per ogni livello e' in rules.js (XP_TABLE)
